application: wagtaildemo
version: 1
runtime: python27
api_version: 1
threadsafe: true
instance_class: F4

automatic_scaling:
  min_idle_instances: 0
  max_concurrent_requests: 12

libraries:
- name: PIL
  version: latest
- name: ssl
  version: latest
- name: MySQLdb
  version: latest

inbound_services:
- warmup

handlers:
- url: /static/
  static_dir: static/
  application_readable: true

- url: .*
  script: demo.wsgi.application
  login: admin
  
skip_files:
  - ^(.*/)?#.*#$
  - ^(.*/)?.*~$
  - ^(.*/)?.*\.py[co]$
  - ^(.*/)?.*/RCS/.*$
  - ^(.*/)?\..*$
  - ^(.*/)?\.bak$
  - ^(.*/)?.*\.scss$
  - ^node_modules.*$
  - ^google_appengine.*$
