application: wagtaildemo
version: 1
runtime: python27
api_version: 1
threadsafe: true
instance_class: F4_1G

automatic_scaling:
  min_idle_instances: 1

libraries:
- name: PIL
  version: latest
- name: ssl
  version: latest
- name: MySQLdb
  version: latest

inbound_services:
- warmup

handlers:
- url: /static/
  static_dir: static/
  application_readable: true

#- url: /media/
#  static_dir: media/
#  application_readable: true
#

- url: .*
  script: demo.wsgi.application
